project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Alexander Senetcky"
  site-url: https://asenetcky.dev/
  navbar:
    title: Alexander Senetcky
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
      - projects.qmd
      - presentations.qmd
      - text: Contact
        menu:
          - icon: linkedin
            text: Linkedin
            href: https://www.linkedin.com/in/alexander-senetcky-0b209822
            target: _blank
          - icon: envelope
            text: Email
            href: mailto:me@asenetcky.dev
      - icon: github
        href: https://github.com/asenetcky
        target: _blank
  page-footer:
    left: © 2025 Alexander Senetcky
    right: This website is built with [Quarto]("https://quarto.org/") and [GitHub]("https://github.com")
  draft-mode: unlinked

  repo-url: https://github.com/asenetcky/asenetcky.dev
  repo-actions: [edit, source, issue]

format:
  html:
    page-layout: full
    theme: lux
    css: styles.css
    toc: true

#brand:
#  light: brand/light-brand.yml
#  dark: brand/dark-brand.yml

